# Generated by Django 6.0 on 2025-12-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("quests", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participantskill",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acquired_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participantskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skills.skill"
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quests",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="skills",
            field=models.ManyToManyField(related_name="quests", to="skills.skill"),
        ),
        migrations.AddField(
            model_name="participantskill",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quests.quest"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="quest",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="quests.quest",
            ),
        ),
        migrations.AddField(
            model_name="questprogress",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quest_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questprogress",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="quests.quest",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="quests.quest",
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badge",
                to="quests.task",
            ),
        ),
        migrations.AddField(
            model_name="taskcompletion",
            name="progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_completions",
                to="quests.questprogress",
            ),
        ),
        migrations.AddField(
            model_name="taskcompletion",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quests.task"
            ),
        ),
        migrations.AddField(
            model_name="taskcompletion",
            name="validated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participantskill",
            unique_together={("participant", "skill", "quest")},
        ),
        migrations.AlterUniqueTogether(
            name="questprogress",
            unique_together={("participant", "quest")},
        ),
        migrations.AlterUniqueTogether(
            name="taskcompletion",
            unique_together={("progress", "task")},
        ),
    ]
